### ISSUE TITLE
Fast construction of ray_3D_list

### ISSUE THREAD

**Issue by HTDerekLiu** [rohan-sawhney/fcpw#13]
Hi Rohan,

First, thanks for the great library!

I am using the python version of fcpw. I wonder whether there is a way to construct `ray_3D_list` efficiently for e.g. 1 billion rays? Perhaps I am missing something, it seems like `ray_3D_list` only takes a list of `ray_3D` as input? Assembling 1 billion list of `ray_3D ` in python is taking forever. I wonder whether there is a way to construct `ray_3D_list` by e.g. inputing a np.array of `origins` and a np.array of `directions`?

-Derek

**Comment by rohan-sawhney** [comment]
Hi Derek, thanks for reporting the issue. Working on a fix, will let you know once its in place.

**Comment by rohan-sawhney** [comment]
I've updated the Python API to directly accept numpy arrays, which should speed things up. See [here](https://github.com/rohan-sawhney/fcpw/blob/a9eb7f03fd6d30603f034f8d1671a1855532e87e/tests/fcpw_tests.py#L130) for the CPU ray intersection query, and [here](https://github.com/rohan-sawhney/fcpw/blob/a9eb7f03fd6d30603f034f8d1671a1855532e87e/tests/fcpw_tests.py#L477) for the gpu version. Run `pip install fcpw --force-reinstall` to install these changes.

If you are doing on the order of a billion queries, you might want consider batching the queries, especially on the GPU.

Let me know if you see improved performance.
