### ISSUE TITLE
Primitives defined only in 3D

### ISSUE THREAD

**Issue by ikoruk** [rohan-sawhney/fcpw#7]
Primitives such as line segments and triangles are only defined only in 3D. It would be useful to also have them in 2D for example.

Also fcpw won't compile in 2D without changing `auto it = cs.emplace(cs.end(), Interaction<3>());` in `sbvh.inl` from 3 to DIM.

**Comment by rohan-sawhney** [comment]
@ikoruk for line segments, you could define the z coordinate of each vertex to be zero. Would that work for you?

**Comment by ikoruk** [comment]
That is indeed the fix I went for but it’s not ideal in terms of memory and speed.It would be great as well if there was a way to not store the points in the structure but rather pass them in in each call (like igl’s aabb) to save having a duplicate in memory.On Aug 13, 2023, at 01:15, Rohan Sawhney ***@***.***> wrote:﻿
@ikoruk for line segments, you could define the z coordinate of each vertex to be zero. Would that work for you?

**Comment by ikoruk** [comment]
It's great you are working on this, however I wouldn't really call this completed. It is useful to have triangle queries even in 2D, and conversely line segment queries in 3D.
